name: precision-sweep

on:
  workflow_dispatch:

jobs:
  rtl_test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        data_w: [4, 5, 6, 7, 8, 9]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install uv
        shell: bash
        run: python -m pip install uv

      - name: Sync Python environment
        shell: bash
        run: uv sync

      - name: Run width sweep tests
        shell: bash
        run: |
          uv run make -C test clean
          uv run make -C test COCOTB_RESULTS_FILE=results_rtl_w${{ matrix.data_w }}.xml DATA_W=${{ matrix.data_w }}
          ! grep failure test/results_rtl_w${{ matrix.data_w }}.xml

      - name: Test Summary
        uses: test-summary/action@v2.4
        if: always()
        with:
          paths: "test/results_rtl_w${{ matrix.data_w }}.xml"

      - name: Upload width sweep test artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: rtl-test-w${{ matrix.data_w }}
          path: |
            test/tb.fst
            test/results_rtl_w${{ matrix.data_w }}.xml
            test/output/*
